name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: myacr10691.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - run: |
          docker build -t myacr10691.azurecr.io/flask-demo:latest .
          docker push myacr10691.azurecr.io/flask-demo:latest

      - name: Set AKS context
        uses: azure/aks-set-context@v3
        with:
          resource-group: demo-rg
          cluster-name: my-aks

      - run: |
          kubectl set image deployment/flask-demo flask-demo=myacr10691.azurecr.io/flask-demo:latest
